throttle_pid:
  ros__parameters:
    Kp: 3.0
    Ki: 0.0
    Kd: 0.0
pitch_pid:
  ros__parameters:
    Kp: 0.0
    Ki: 0.0
    Kd: 0.0
roll_pid:
  ros__parameters:
    Kp: 0.0
    Ki: 0.0
    Kd: 0.0
