<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>swift_pico</name>
  <version>1.0.0</version>
  <description>Controller Package for Swift Pico</description>
  <maintainer email="drone@e-yantra.org">eyantra_drone_team</maintainer>
  <license>TODO: License declaration</license>
  <author>Eyantra Drone Team</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>rclcpp</depend>
  <depend>swift_msgs</depend>           
  <depend>controller_msg</depend>      
  <depend>error_msg</depend>            
  <depend>geometry_msgs</depend>        
  <depend>whycode_interfaces</depend>   

  <depend>rosgraph_msgs</depend>      
  <depend>sensor_msgs</depend>          
  <depend>actuator_msgs</depend>      
  <depend>nav_msgs</depend>            
  
  <depend>ament_index_python</depend>
  <depend>ament_index_cpp</depend>
  <depend>libopencv-dev</depend>
  <depend>builtin_interfaces</depend>
  <depend>libglfw3-dev</depend>

  <exec_depend>swift_pico_description</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>image_view</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>